### ISSUE TITLE
Show download button for open-access works

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/opds-browser#126]
James requested this feature for demos as it will show how the OPDS browser would work as a full reading environment.

The LS circ manager includes an open-access link for open-access books, e.g.:

`<link href="http://oabooks.nypl.org/Project%20GITenberg/Gutenberg%20ID/2701.epub" rel="http://opds-spec.org/acquisition/open-access" type="application/epub+zip">`

If an open-access link shows up in an OPDS entry, show a 'Read' button that downloads the open-access book when clicked.

**Comment by jce1028** [comment]
I think we should call the button "get" to be consistent with mobile clients.  Unless we think that Read will help differentiate that it is a direct acquisition rather than indirect acquisition...albeit users don know or care about the difference.   In MAC downloading an EPUB (e.g. "Get") will automatically open iBooks and given the files extension because the .EPUB extension is associated with that app.  I don't know what Chrome OS, Linux OS or Windows OS will do in terms of recognizing the extension.  They may just ask you to associate it with a default app.

**Comment by aslagle** [comment]
This is deployed to the heroku app.
